export enum ErrorCode {
	UNKNOWN_ERROR = "GENERIC.UNKNOWN",
	VALIDATION_ERROR = "VALIDATION.FAILED",
	RATE_LIMIT_EXCEEDED = "SECURITY.RATE_LIMIT_EXCEEDED",

	// General / security errors
	TOKEN_INVALID_OR_EXPIRED = "AUTH.TOKEN_INVALID_OR_EXPIRED",
	UNEXPECTED_ERROR = "GENERIC.UNEXPECTED",
	RESOURCE_NOT_FOUND_OR_FORBIDDEN = "GENERIC.RESOURCE_NOT_FOUND_OR_FORBIDDEN",
	DO_NOT_JUST_MESS_WITH_ME = "SECURITY.DO_NOT_JUST_MESS_WITH_ME",

	// Account / auth errors
	ACCOUNT_DELETED_OR_NOT_FOUND = "AUTH.ACCOUNT_DELETED_OR_NOT_FOUND",
	ACCOUNT_ALREADY_EXISTS = "AUTH.ACCOUNT_ALREADY_EXISTS",
	ACCOUNT_ALREADY_VERIFIED = "AUTH.ACCOUNT_ALREADY_VERIFIED",
	ACCOUNT_BANNED = "AUTH.ACCOUNT_BANNED",
	ACCOUNT_NOT_VERIFIED = "AUTH.ACCOUNT_NOT_VERIFIED",
	ACCOUNT_NOT_ACTIVE = "AUTH.ACCOUNT_NOT_ACTIVE",
	ACCOUNT_NOT_AUTHORIZED = "AUTH.ACCOUNT_NOT_AUTHORIZED",
	MFA_METHOD_NOT_SUPPORTED = "AUTH.MFA_METHOD_NOT_SUPPORTED",
	ACCOUNT_CAN_NOT_RE_ACTIVATE = "AUTH.ACCOUNT_CAN_NOT_REACTIVATE",
	SESSION_NOT_FOUND = "AUTH.SESSION_NOT_FOUND",
	CAN_NOT_UPLOAD_AVATAR = "USER.AVATAR_UPLOAD_FAILED",

	// Password / credential errors
	INVALID_CREDENTIALS = "AUTH.INVALID_CREDENTIALS",
	PASSWORD_MISMATCH = "AUTH.PASSWORD_MISMATCH",
	PASSWORD_MUST_UPDATE_BEFORE_6_MONTHS = "AUTH.PASSWORD_MUST_UPDATE_BEFORE_6_MONTHS",
	PASSWORD_DUPLICATE = "AUTH.PASSWORD_DUPLICATE",
	PASSWORD_COMPROMISED = "AUTH.PASSWORD_COMPROMISED",
	PASSWORD_RESET_REQUIRED = "AUTH.PASSWORD_RESET_REQUIRED",

	// Data hub errors
	CURRENCY_ALREADY_EXISTS = "DATA.CURRENCY_ALREADY_EXISTS",
	CURRENCY_NOT_FOUND = "DATA.CURRENCY_NOT_FOUND",
	CAN_NOT_GET_EXCHANGE_RATE = "DATA.CAN_NOT_GET_EXCHANGE_RATE",
	CAN_NOT_UPLOAD_FILE = "FILE.CAN_NOT_UPLOAD",
	FILE_INVALID_TYPE = "FILE.INVALID_TYPE",
	CAN_NOT_VIEW_FILE = "FILE.CAN_NOT_VIEW",
	CAN_NOT_DELETE_FILE = "FILE.CAN_NOT_DELETE",
	ASSET_SHARE_FAILED = "ASSET.SHARE_FAILED",
	ASSET_UNSHARE_FAILED = "ASSET.UNSHARE_FAILED",

	// Transaction / wallet errors
	TRANSACTION_NOT_FOUND = "TRANSACTION.NOT_FOUND",
	AMOUNT_MUST_BE_POSITIVE = "TRANSACTION.AMOUNT_MUST_BE_POSITIVE",
	FEE_MUST_BE_POSITIVE = "TRANSACTION.FEE_MUST_BE_POSITIVE",
	AMOUNT_MUST_BE_LARGER_THAN_FEE = "TRANSACTION.AMOUNT_MUST_BE_LARGER_THAN_FEE",
	CAN_NOT_USE_THIS_WALLET = "WALLET.CAN_NOT_USE",
	WALLET_NOT_ENOUGH_BALANCE = "WALLET.NOT_ENOUGH_BALANCE",
	AMOUNT_MUST_BE_NEGATIVE = "TRANSACTION.AMOUNT_MUST_BE_NEGATIVE",
	WALLET_NOT_FOUND_OR_FORBIDDEN = "WALLET.NOT_FOUND_OR_FORBIDDEN",
	WALLET_LOCKED = "WALLET.LOCKED",
	CAN_NOT_DELETE_WALLET_WITH_BALANCE = "WALLET.CAN_NOT_DELETE_WITH_BALANCE",

	// Category / Subscription / Payment errors can be added as needed
}
